drop table book cascade constraints;
CREATE TABLE "BOOK" 
   (	
   	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
   "ISBN" VARCHAR2(20) UNIQUE, 
	"TITLE" VARCHAR2(50), 
	"AUTHOR_LAST_NAME" VARCHAR2(30), 
	"AUTHOR_FIRST_NAME" VARCHAR2(30), 
	"RATING" NUMBER,
    primary key (id)
   ) ;
REM INSERTING into BOOKS
SET DEFINE OFF;
Insert into BOOK (ISBN,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A1111','HP1','Melville','Herman','5,5');
Insert into BOOK (ISBN,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A2222','ssss','Scammer','Ima','7');
Insert into BOOK (ISBN,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A3333','QQQQQ','Blissford','Serenity','3,5');
Insert into BOOK (ISBN,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A4444','YYY','Whodunit','Rodney','3,5');
Insert into BOOK (ISBN,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A5555','HP2','Abugov','Herman','6');
commit;
